### PR TITLE
Visualize profile

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by Rdataflow** [comment]
@tpluscode great to see you're on this now 😄 
can you add checks for and make mandatory for visualize: 
- [ ] minCount 1 for sh:path sh:nodeKind 
  - WRT https://github.com/visualize-admin/visualization-tool/pull/1181
  - https://github.com/visualize-admin/visualization-tool/issues/1180
  - NB: todays data is already compliant https://s.zazuko.com/3muDEnJ 👍 
- [ ] minCount 1 for sh:path qudt:scaleType
  - WRT https://github.com/zazuko/cube-shacl-validation/issues/16
  - only a handful of dimensions can be republished https://s.zazuko.com/2zhEXrq - the maintainers are well known 👍 

THNX - this will greatly improve the data quality and fix situations we've had in the past again and again

cc @bprusinowski @claudiodigallo

**Comment by tpluscode** [comment]
@Rdataflow 

> * minCount 1 for sh:path sh:nodeKind

Looking at the linked PR, would I also add a requirement that only `sh:IRI` and `sh:Literal` are allowed? Does any other value (`sh:BlankNode`, `sh:BlankNodeOrIRI`, `sh:IRIOrLiteral`, `sh:BlankNodeOrLiteral`) make sense?

**Comment by tpluscode** [comment]
> * minCount 1 for sh:path qudt:scaleType

What are the pitfalls of not having a scale type? @Rdataflow

**Comment by Rdataflow** [comment]
> @Rdataflow
> 
> > * minCount 1 for sh:path sh:nodeKind
> 
> Looking at the linked PR, would I also add a requirement that only `sh:IRI` and `sh:Literal` are allowed? Does any other value (`sh:BlankNode`, `sh:BlankNodeOrIRI`, `sh:IRIOrLiteral`, `sh:BlankNodeOrLiteral`) make sense?

@giacomociti :100:  - there is only `sh:IRI` and `sh:Literal` in the cubes - and visualize only supports that

**Comment by Rdataflow** [comment]
> @Rdataflow
> 
> > * minCount 1 for sh:path sh:nodeKind
> 
> Looking at the linked PR, would I also add a requirement that only `sh:IRI` and `sh:Literal` are allowed? Does any other value (`sh:BlankNode`, `sh:BlankNodeOrIRI`, `sh:IRIOrLiteral`, `sh:BlankNodeOrLiteral`) make sense?

@tpluscode  💯 - there is only sh:IRI and sh:Literal in the cubes - and visualize only supports that

**Comment by Rdataflow** [comment]
> > * minCount 1 for sh:path qudt:scaleType
> 
> What are the pitfalls of not having a scale type? @Rdataflow
> 
> To be honest, I actually don't think it's correct to require a scale type. The available options (`qudt:IntervalScale`, `qudt:NominalScale`, `qudt:EnumerationScale`, `qudt:RatioScale`, `qudt:OrdinalScale`) do not cover all possibilities

@tpluscode thanks for asking. while for a basic cube this is optional, for visualize it's a requirement to give a scaleType. (there may be lucky cases where the charts maybe appear as a publisher intended - but that's by pure luck and might change at any time) 
else visualize would need to guess how to order tables, would need to guess whether to print charts on an absolute scale starting at 0, would generate inadequate queries leading to poor performance, and would mix up the chart logic for cubes missing this dimension, like we already had while prototyping new pipelines...

while there are additional RDF properties at hand - for `qudt:scaleType` the cube Spec only distinguishes 4 scaleTypes https://cube.link/#qudt-scaletype
`qudt:IntervalScale`, `qudt:NominalScale`, `qudt:RatioScale`, `qudt:OrdinalScale`
visualize only supports those 4 types.
they are generic enough to fit all kind of cases:
- Nominal (named variables): categories, species, regions, ...
- Ordinal (+ ordered variables): warning levels, threat categories, ordinal time intervals, ...
- Interval (+ proportionate interval between variables): absolute height of places, point in time, grades, lake level, ...
- Ratio (+ can accommodate absolute zero): count, density, flow, ...
see also https://github.com/zazuko/cube-creator/wiki/3.-Cube-Designer#scale-of-measure

LINDAS only features those 4 types:
https://s.zazuko.com/DAKpCS

cc @bprusinowski

**Comment by bprusinowski** [comment]
Hey 👋 I am pasting the comment from Zulip to move the conversation about data types here – I think it would make sense to have some validation to only allow one, non-undefined data type.

> Not 100% related to scale types, but also in the area of validations – will there be some check on data types? I just stumbled upon Elcom cube which has two data types assigned to it (see [PR](https://github.com/visualize-admin/visualization-tool/pull/1397) for broad context, or [SPARQL query](https://lindas.admin.ch/sparql/?lang=en)).
> 
> We are using cube-view-query to get information on data type, which uses this.ptr.out(ns.sh.datatype).term to extract this info (see https://github.com/zazuko/rdf-cube-view-query/blob/master/lib/CubeDimension.js#L20-L25) – I guess that's not something anticipated then? I needed to modify the code to also check for this.ptr.out(ns.sh.datatype).terms and take the first data type found.
> 
> I am not sure if this cube goes through some validation? Just wanted to bring this topic up, I think it doesn't make a lot of sense to have two data types defined like that (decimal and float)?

cc @Rdataflow @ptbrowne

**Comment by Rdataflow** [comment]
one more important finding: 
- [ ] the visualize profile should check `meta:dataKind` only has nodes with attributes in `rdf:type`, `time:unitType` but nothing else i.e. no `rdf:first`, `rdf:rest`, or whatever else... (at least it should throw a warning in such cases) 
   - see https://s.zazuko.com/2M4cXUu returns a rdfList nested within `meta:dataKind` unexpectedly

**Comment by tpluscode** [comment]
@bprusinowski the existence of multiple datatypes is already checked 👌 
@Rdataflow just pushed that too. A warning will be raised if `meta:dataKind` is not one of the three defined types. Also, each on will cause a violation error if they contain extra properties: `GeoShape` and `GeoCoordinates` do not allow anything other than their type and `time:GeneralDatTimeDescription` will only allow an additional `time:unitType`.

**Comment by Rdataflow** [comment]
@tpluscode here the rest of my completed review
- [ ] the visualize profile (or at your choice standalone-constraint) shall check a dimension effectively has 
   ```rdf
   sh:minCount 1 ;
   sh:maxCount 1 ;
   ```

    <details>
    maybe by adding a check per dimension for

    ```rdf
    sh:path sh:minCount ;
    sh:hasValue 1 ;
    ....
    sh:path sh:maxCount ;
    sh:hasValue 1 ;
    ```

    </details>
- [ ] the visualize profile (or at your choice standalone-constraint) shall conditionally check in cases where `qudt:unit` exists to also have `qudt:hasUnit` and give a hint for the upcoming deprecation...
- [ ] enforce to have a `qudt:scaleType` - so visualize can truly rely on it...

**Comment by tpluscode** [comment]
@Rdataflow just pushed these three validations.

min/max and warning about `qudt:unit` added to `standalone-constraint`
I also could have sworn that I'd already done the scale type. Anyway, it's there now

**Comment by Rdataflow** [comment]
@tpluscode 🙇 just one last thing I forgot to mention earlier:
- [ ] check for `sh:in` in case of `scaleType == Nominal|Ordinal && type == KeyDimension` with severity INFO: "for performance reason add list of ocurring elements"

**Comment by Rdataflow** [comment]
@tpluscode LGTM

**Review by giacomociti — APPROVED** [review]

**Pull request merged**
