### PR TITLE
test: use @zazuko/shacl-test

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by tpluscode** [comment]
@giacomociti could you try making the `npm test:*` scripts working on windows? I don't understand the reason for error here

**Comment by giacomociti** [comment]
I can reproduce the issue on Windows. Apparently, it's the file path separator

**Comment by tpluscode** [comment]
The question is, can you fix it? :)

**Comment by tpluscode** [comment]
🚀

**Review by giacomociti — APPROVED** [review]

**Pull request merged**
